create table if not exists public.event_settings (
  id text primary key,
  current_event_id text not null default 'event-1',
  registration_open boolean not null default true,
  round text not null default 'lobby',
  started_at timestamptz
);

create table if not exists public.participants (
  id uuid primary key,
  event_id text not null default 'event-1',
  name text not null,
  college text not null,
  department text not null,
  year text not null,
  score integer not null default 0,
  status text not null default 'ready',
  round_scores jsonb not null default '{"round1":0,"round2":0,"round3":0}'::jsonb,
  quiz_questions jsonb not null default '[]'::jsonb,
  draft_answers jsonb not null default '{}'::jsonb,
  quiz_started_at timestamptz,
  quiz_submitted_at timestamptz,
  joined_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.participants(id) on delete cascade,
  question_id text not null,
  answer text not null,
  correct boolean not null,
  points integer not null default 0,
  submitted_at timestamptz not null default now()
);

create table if not exists public.question_bank (
  id text primary key,
  round text,
  topic text not null default 'General technology',
  difficulty text not null default 'medium',
  question_type text not null default 'mcq',
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  answer text,
  points integer not null default 100,
  time_limit_seconds integer,
  explanation text,
  is_active boolean not null default true
);

alter table public.question_bank alter column round drop not null;
alter table public.question_bank add column if not exists topic text not null default 'General technology';
alter table public.question_bank add column if not exists difficulty text not null default 'medium';
alter table public.question_bank add column if not exists question_type text not null default 'mcq';
alter table public.question_bank add column if not exists explanation text;
alter table public.question_bank add column if not exists is_active boolean not null default true;
alter table public.event_settings add column if not exists current_event_id text not null default 'event-1';
alter table public.participants add column if not exists event_id text not null default 'event-1';
alter table public.participants add column if not exists quiz_questions jsonb not null default '[]'::jsonb;
alter table public.participants add column if not exists draft_answers jsonb not null default '{}'::jsonb;
alter table public.participants add column if not exists quiz_started_at timestamptz;
alter table public.participants add column if not exists quiz_submitted_at timestamptz;

insert into public.event_settings (id)
values ('main')
on conflict (id) do nothing;

create index if not exists participants_event_id_idx on public.participants(event_id);

alter table public.event_settings enable row level security;
alter table public.participants enable row level security;
alter table public.submissions enable row level security;
alter table public.question_bank enable row level security;
